apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-blue
data:
  index.html: |
    <!DOCTYPE html>
    <html>
    <head>
        <title>Blue Deployment</title>
    </head>
    <body>
        <h1>This is the Blue Deployment</h1>
    </body>
    </html>